# Generated by Django 5.2.4 on 2026-05-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReelProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, default='', max_length=255)),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('format_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_duration_seconds', models.PositiveIntegerField(default=30)),
                ('slide_count', models.PositiveIntegerField(default=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('slide_type', models.CharField(choices=[('hook', 'Hook'), ('katex', 'KaTeX'), ('cumulative_katex', 'Cumulative KaTeX'), ('result', 'Result'), ('cta', 'CTA')], max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('screen_text', models.TextField(blank=True, default='')),
                ('katex', models.TextField(blank=True, default='')),
                ('voice_script', models.TextField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(default=4)),
                ('layout_status', models.CharField(choices=[('unchecked', 'Unchecked'), ('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], default='unchecked', max_length=32)),
                ('layout_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='reel_studio.reelproject')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('reel_project', 'order')},
            },
        ),
    ]
