# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelslide',
            name='title_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='reelslide',
            name='screen_text_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='reelslide',
            name='katex_scale',
            field=models.FloatField(default=1.0),
        ),
    ]
