# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_studio', '0002_reelslide_manual_size_scales'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelslide',
            name='katex_inline_with_previous',
            field=models.BooleanField(default=False),
        ),
    ]
