# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_studio', '0003_reelslide_katex_inline_with_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelslide',
            name='katex_reset_cumulative',
            field=models.BooleanField(default=False),
        ),
    ]
