# Generated by Django 5.2.4 on 2026-05-17 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_studio', '0020_reelslide_katex_reset_keep_previous_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='carousel_generation', max_length=64)),
                ('model_id', models.CharField(max_length=128)),
                ('prompt_token_count', models.PositiveIntegerField(default=0)),
                ('candidates_token_count', models.PositiveIntegerField(default=0)),
                ('thoughts_token_count', models.PositiveIntegerField(default=0)),
                ('total_token_count', models.PositiveIntegerField(default=0)),
                ('input_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('output_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('total_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('pricing_source', models.CharField(blank=True, default='', max_length=255)),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('response_chars', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_usage_logs', to='reel_studio.reelproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='reel_studio_created_9c5bcb_idx'), models.Index(fields=['model_id'], name='reel_studio_model_i_b81a25_idx')],
            },
        ),
    ]
