# Generated by Django 5.2.4 on 2026-05-17

import reel_studio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_studio', '0021_geminiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelslide',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to=reel_studio.models.reel_slide_generated_image_upload_to),
        ),
        migrations.AddField(
            model_name='reelslide',
            name='generated_image_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reelslide',
            name='generated_image_model_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reelslide',
            name='generated_image_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
