# Generated by Django 5.2.4 on 2025-11-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0010_matiere_show_on_home'),
        ('pays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeLearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('accroche', models.CharField(blank=True, max_length=200)),
                ('resource_type', models.CharField(choices=[('course', 'Cours'), ('exercise', 'Exercice'), ('summary', 'Résumé')], max_length=20)),
                ('excerpt', models.TextField(blank=True)),
                ('contenu_html', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=60)),
                ('lecture_duree', models.CharField(blank=True, max_length=60)),
                ('tag_secondaire', models.CharField(blank=True, max_length=60)),
                ('est_publie', models.BooleanField(default=False)),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_resources', to='curriculum.matiere')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_resources', to='pays.niveau')),
                ('notion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_resources', to='curriculum.notion')),
            ],
            options={
                'verbose_name': 'Ressource gratuite',
                'verbose_name_plural': 'Ressources gratuites',
                'ordering': ['resource_type', 'ordre', 'titre'],
            },
        ),
    ]
