# Generated by Django 5.2.4 on 2025-11-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formule_type', models.CharField(choices=[('essentiel', 'Essentiel'), ('intensif', 'Intensif'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_cours', models.DateTimeField(blank=True, null=True)),
                ('duree_heures', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('status', models.CharField(choices=[('reserve', 'Réservé'), ('termine', 'Terminé - En attente de paiement'), ('paye', 'Payé'), ('annule', 'Annulé')], default='reserve', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('notes_professeur', models.TextField(blank=True)),
                ('notes_parent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cours_particuliers.formulecours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_cours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reservation'],
                'indexes': [models.Index(fields=['user', 'status'], name='cours_parti_user_id_e86c5c_idx'), models.Index(fields=['date_cours'], name='cours_parti_date_co_52741f_idx')],
            },
        ),
    ]
