services:
  # Backend Django API
  - type: web
    name: optitab-backend
    runtime: python3
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn backendAPI.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: backendAPI.settings
      - key: ALLOWED_HOSTS
        value: optitab.net,www.optitab.net,optitab-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://optitab.net,https://www.optitab.net
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /api/health/

  # Frontend Vue.js
  - type: web
    name: optitab-frontend
    runtime: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run serve"
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://optitab-backend.onrender.com/api
    routes:
      - type: redirect
        source: /api/(.*)
        destination: https://optitab-backend.onrender.com/api/$1
        status: 200

# Base de données PostgreSQL
databases:
  - name: optitab-db
    databaseName: optitab
    user: optitab_user
    plan: starter
