services:
  - type: static
    name: optitab-frontend
    rootDirectory: frontend
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
  - type: web
    name: optitab-backend
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backendAPI.settings
      - key: PYTHONPATH
        value: /opt/render/project/src/backend:/opt/render/project/src
      - key: FRONTEND_BASE_URL
        value: https://www.optitab.net
