# Generated by Django 5.2.4 on 2025-08-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0005_exercice_etapes'),
    ]

    operations = [
        # Supprimer d'abord la table existante si elle existe
        migrations.RunSQL(
            "DROP TABLE IF EXISTS synthesis_synthesissheet CASCADE;",
            reverse_sql="-- Pas de rollback pour cette opération"
        ),
        
        # Créer le nouveau modèle
        migrations.CreateModel(
            name='SynthesisSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('summary', models.TextField(help_text='Contenu principal de la fiche en Markdown', verbose_name='Résumé')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10, verbose_name='Difficulté')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='Liste des points essentiels à retenir', verbose_name='Points clés')),
                ('formulas', models.JSONField(blank=True, default=list, help_text='Formules mathématiques importantes', verbose_name='Formules')),
                ('examples', models.JSONField(blank=True, default=list, help_text="Exemples concrets d'application", verbose_name='Exemples')),
                ('reading_time_minutes', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthesis_sheets', to='curriculum.notion')),
            ],
            options={
                'verbose_name': 'Fiche de synthèse',
                'verbose_name_plural': 'Fiches de synthèse',
                'ordering': ['notion', 'ordre'],
                'unique_together': {('notion', 'titre')},
            },
        ),
    ]
