# Generated by Django 5.2.4 on 2025-08-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheSynthese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('contenu_markdown', models.TextField()),
                ('notion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche', to='curriculum.notion')),
            ],
            options={
                'verbose_name': 'Fiche de Synthèse',
                'verbose_name_plural': 'Fiches de Synthèse',
                'ordering': ['notion'],
            },
        ),
    ]
