# Generated by Django 5.2.4 on 2025-11-01 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        # Some databases or older states may not have the old index; make the rename safe.
        migrations.RunSQL(
            sql=(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_class WHERE relname = 'subscriptions_user_end_idx'
                    ) THEN
                        ALTER INDEX subscriptions_user_end_idx RENAME TO subscriptio_user_id_0cd826_idx;
                    END IF;
                END$$;
                """
            ),
            reverse_sql=(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_class WHERE relname = 'subscriptio_user_id_0cd826_idx'
                    ) THEN
                        ALTER INDEX subscriptio_user_id_0cd826_idx RENAME TO subscriptions_user_end_idx;
                    END IF;
                END$$;
                """
            ),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
