# Generated by Django 5.2.4 on 2025-11-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_rename_subscriptions_user_end_idx_subscriptio_user_id_0cd826_idx'),
    ]

    operations = [
        migrations.RunSQL(
            sql=
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_class WHERE relname = 'subscriptions_user_end_idx'
                    ) THEN
                        ALTER INDEX subscriptions_user_end_idx RENAME TO subscriptio_user_id_0cd826_idx;
                    END IF;
                END$$;
                """,
            reverse_sql=
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_class WHERE relname = 'subscriptio_user_id_0cd826_idx'
                    ) THEN
                        ALTER INDEX subscriptio_user_id_0cd826_idx RENAME TO subscriptions_user_end_idx;
                    END IF;
                END$$;
                """,
        ),
    ]
