# Generated by Django 5.2.4 on 2025-11-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_add_access_days_if_missing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionplan',
            name='subscriptionplan_unique_pt_bp_planmode',
        ),
        migrations.RenameIndex(
            model_name='accesspass',
            new_name='subscriptio_user_id_0cd826_idx',
            old_name='subscriptions_user_end_idx',
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='plan',
            field=models.ForeignKey(limit_choices_to={'plan_mode': 'one_time'}, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan'),
        ),
    ]
