# Generated by Django 5.2.4 on 2025-11-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_subscriptionplan_subscriptionplan_unique_pt_bp_planmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(choices=[('daily', 'Journalier'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=20),
        ),
    ]
