# Generated by Django 5.2.4 on 2025-11-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0001_initial'),
        ('subscriptions', '0015_usersubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='niveau_pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='pays.niveau'),
        ),
    ]
