# Generated by Django 5.2.4 on 2025-11-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0001_initial'),
        ('subscriptions', '0017_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='niveau_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='niveau_pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history_entries', to='pays.niveau'),
        ),
    ]
