# Generated by Django 5.2.4 on 2025-11-10 00:00

from django.db import migrations, models


PLAN_MODE_CHOICES = [
    ('subscription', 'Abonnement récurrent'),
    ('one_time', 'Pass ponctuel'),
    ('payment', 'Paiement simple'),
]


def _clean_suffix(value):
    return value.strip(" .:-–—()")


def populate_plan_fields(apps, schema_editor):
    PaymentHistory = apps.get_model('subscriptions', 'PaymentHistory')

    for payment in PaymentHistory.objects.all().iterator():
        description = payment.description or ''
        normalized = description.lower()

        if payment.stripe_invoice_id or 'paiement pour' in normalized:
            mode = 'subscription'
        elif 'pass' in normalized:
            mode = 'one_time'
        else:
            mode = 'payment'

        plan_name = ''
        if mode == 'subscription':
            marker = 'paiement pour'
            if marker in normalized:
                idx = normalized.index(marker) + len(marker)
                plan_name = _clean_suffix(description[idx:])
            else:
                plan_name = _clean_suffix(description)
        elif mode == 'one_time':
            marker = 'pass'
            if marker in normalized:
                idx = normalized.index(marker) + len(marker)
                plan_name = _clean_suffix(description[idx:])
            else:
                plan_name = _clean_suffix(description)
        else:
            plan_name = _clean_suffix(description)

        payment.plan_mode = mode
        payment.plan_name = plan_name
        payment.save(update_fields=['plan_mode', 'plan_name'])


def reverse_populate_plan_fields(apps, schema_editor):
    PaymentHistory = apps.get_model('subscriptions', 'PaymentHistory')
    PaymentHistory.objects.all().update(plan_mode='payment', plan_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_paymenthistory_niveau_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='plan_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='plan_mode',
            field=models.CharField(choices=PLAN_MODE_CHOICES, default='payment', max_length=20),
        ),
        migrations.RunPython(populate_plan_fields, reverse_populate_plan_fields),
    ]

