# Generated by Django 5.2.4 on 2026-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_paymenthistory_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspass',
            name='expiration_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
