# Generated by Django 5.2.4 on 2026-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_add_expiration_email_sent_to_accesspass'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspass',
            name='is_revoked',
            field=models.BooleanField(default=False, help_text='Pass révoqué suite à un remboursement'),
        ),
        migrations.AddField(
            model_name='accesspass',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
