# Generated by Django 5.2.4 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_add_revoked_fields_to_accesspass'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_test',
            field=models.CharField(
                blank=True,
                help_text='Price ID Stripe en mode test (utilisé en local/dev).',
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
