# Generated by Django 5.2.4 on 2026-07-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_subscriptionplan_stripe_price_id_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('accompagne', 'Accompagne (questions illimitees)'), ('particuliers', 'Cours particuliers')], max_length=20),
        ),
    ]
