# Generated by Django 5.2.4 on 2026-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_alter_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant reellement demande a Stripe, en euros.', max_digits=8, verbose_name='Montant')),
                ('label', models.CharField(blank=True, help_text='Ex. « Cours du 12 mars, 2h ». Visible par le payeur.', max_length=140, verbose_name='Objet')),
                ('payer_name', models.CharField(blank=True, max_length=120, verbose_name='Nom du payeur')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du payeur')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Paye'), ('expired', 'Abandonne'), ('refunded', 'Rembourse')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('stripe_session_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paye le')),
            ],
            options={
                'verbose_name': 'Versement cours particulier',
                'verbose_name_plural': 'Versements cours particuliers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='subscriptio_status_287cac_idx')],
            },
        ),
    ]
