# Generated by Django 5.2.4 on 2025-08-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cours_images/')),
                ('image_type', models.CharField(choices=[('illustration', 'Illustration')], default='illustration', max_length=20)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('legende', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cours.cours')),
            ],
            options={
                'verbose_name': 'Image de cours',
                'verbose_name_plural': 'Images de cours',
                'ordering': ['cours', 'position', 'id'],
                'indexes': [models.Index(fields=['cours', 'position'], name='cours_cours_cours_i_f3f936_idx')],
            },
        ),
    ]
