# Generated by Django 5.2.4 on 2025-09-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_coursimage'),
        ('curriculum', '0006_alter_theme_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['notion'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='chapitre',
        ),
        migrations.AddField(
            model_name='cours',
            name='notion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='curriculum.notion'),
        ),
    ]
