# Generated by Django 5.2.4 on 2025-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_cours_options_remove_cours_chapitre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='cours_pdfs/'),
        ),
    ]
