# Generated by Django 5.2.4 on 2025-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_cours_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='access_scope',
            field=models.CharField(choices=[('paid', 'Abonnés uniquement'), ('free', 'Gratuit (découverte)'), ('both', 'Gratuit + Abonnés')], default='paid', help_text='Définit si ce contenu est gratuit, payant ou visible dans les deux parcours.', max_length=10),
        ),
    ]
