# Generated by Django 5.2.4 on 2025-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_cours_access_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='access_scope',
            field=models.CharField(choices=[('paid', 'Abonnés uniquement'), ('free', 'Gratuit (découverte)'), ('both', 'Gratuit + Abonnés')], default='paid', help_text='Définit si le cours est gratuit, payant ou visible dans les deux parcours.', max_length=10),
        ),
    ]
