# Generated by Django 5.2.4 on 2026-02-27 00:00

import re
from pathlib import Path

from django.db import migrations, models
from django.db.models import Q


def _humanize_filename(filename_or_path):
    raw = str(filename_or_path or "").strip()
    if not raw:
        return ""
    stem = Path(raw).stem
    cleaned = re.sub(r"[_\-]+", " ", stem)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if not cleaned:
        return ""
    return cleaned[0].upper() + cleaned[1:]


def resequence_positions_and_fill_seo(apps, schema_editor):
    CoursImage = apps.get_model("cours", "CoursImage")

    queryset = (
        CoursImage.objects
        .select_related("cours", "cours__notion")
        .order_by("cours_id", "position", "id")
    )

    current_course_id = None
    next_position = 0
    to_update = []

    for image_obj in queryset:
        if image_obj.cours_id != current_course_id:
            current_course_id = image_obj.cours_id
            next_position = 0

        next_position += 1
        changed = False

        if image_obj.position != next_position:
            image_obj.position = next_position
            changed = True

        raw_alt = str(getattr(image_obj, "alt_text", "") or "").strip()
        if not raw_alt:
            legende = str(getattr(image_obj, "legende", "") or "").strip()
            if legende:
                fallback_alt = legende
            else:
                cours = getattr(image_obj, "cours", None)
                course_title = str(getattr(cours, "titre", "") or "").strip()
                if not course_title and cours is not None:
                    notion = getattr(cours, "notion", None)
                    course_title = str(getattr(notion, "titre", "") or "").strip()
                humanized_name = _humanize_filename(getattr(getattr(image_obj, "image", None), "name", ""))
                if course_title and humanized_name:
                    fallback_alt = f"{course_title} - {humanized_name}"
                elif course_title:
                    fallback_alt = f"{course_title} - illustration"
                elif humanized_name:
                    fallback_alt = humanized_name
                else:
                    fallback_alt = "Illustration de cours"
            image_obj.alt_text = fallback_alt
            changed = True

        raw_title = str(getattr(image_obj, "title_text", "") or "").strip()
        if not raw_title:
            fallback_title = _humanize_filename(getattr(getattr(image_obj, "image", None), "name", ""))
            if fallback_title:
                image_obj.title_text = fallback_title
                changed = True

        if changed:
            to_update.append(image_obj)

    if to_update:
        CoursImage.objects.bulk_update(
            to_update,
            ["position", "alt_text", "title_text"],
            batch_size=1000,
        )


def reverse_noop(apps, schema_editor):
    # Reversion intentionally keeps generated SEO content.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0006_alter_cours_access_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursimage",
            name="alt_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="coursimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursimage",
            name="title_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="coursimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(resequence_positions_and_fill_seo, reverse_noop),
        migrations.AddConstraint(
            model_name="coursimage",
            constraint=models.UniqueConstraint(
                condition=Q(position__isnull=False),
                fields=("cours", "position"),
                name="unique_coursimage_position_per_cours",
            ),
        ),
    ]
