# Generated by Django 5.2.4 on 2025-10-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='synthesis_images/')),
                ('image_type', models.CharField(choices=[('illustration', 'Illustration')], default='illustration', max_length=20)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='synthesis.synthesissheet')),
            ],
            options={
                'verbose_name': 'Image de fiche de synthèse',
                'verbose_name_plural': 'Images de fiches de synthèse',
                'ordering': ['sheet', 'position', 'id'],
                'indexes': [models.Index(fields=['sheet', 'position'], name='synthesis_s_sheet_i_c0056c_idx')],
            },
        ),
    ]
