# Generated by Django 5.2.4 on 2025-10-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0002_synthesisimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synthesissheet',
            options={'ordering': ['notion', 'titre'], 'verbose_name': 'Fiche de synthèse', 'verbose_name_plural': 'Fiches de synthèse'},
        ),
    ]
