# Generated by Django 5.2.4 on 2025-11-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0004_synthesissheet_access_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthesissheet',
            name='access_scope',
        ),
    ]
