# Generated by Django 5.2.4 on 2025-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0005_remove_synthesissheet_access_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesissheet',
            name='access_scope',
            field=models.CharField(
                choices=[('paid', 'Abonnés uniquement'), ('free', 'Gratuit (découverte)'), ('both', 'Gratuit + Abonnés')],
                default='paid',
                help_text='Définit si cette fiche est gratuite, payante ou visible dans les deux parcours.',
                max_length=10,
            ),
        ),
    ]
