# Generated by Django 5.2.4 on 2026-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0008_synthesissheet_sheet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthesissheet',
            name='sheet_type',
            field=models.CharField(choices=[('summary', 'Fiche de synthèse'), ('table', 'Tableau & Formules')], db_index=True, default='summary', help_text='Définit le type de fiche (synthèse ou tableau/formules).', max_length=10),
        ),
    ]
