# Generated by Django 5.2.4 on 2026-02-27 00:00

import re
from pathlib import Path

from django.db import migrations, models
from django.db.models import Q


def _humanize_filename(filename_or_path):
    raw = str(filename_or_path or "").strip()
    if not raw:
        return ""
    stem = Path(raw).stem
    cleaned = re.sub(r"[_\-]+", " ", stem)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if not cleaned:
        return ""
    return cleaned[0].upper() + cleaned[1:]


def resequence_positions_and_fill_seo(apps, schema_editor):
    SynthesisImage = apps.get_model("synthesis", "SynthesisImage")

    queryset = (
        SynthesisImage.objects
        .select_related("sheet", "sheet__notion")
        .order_by("sheet_id", "position", "id")
    )

    current_sheet_id = None
    next_position = 0
    to_update = []

    for image_obj in queryset:
        if image_obj.sheet_id != current_sheet_id:
            current_sheet_id = image_obj.sheet_id
            next_position = 0

        next_position += 1
        changed = False

        if image_obj.position != next_position:
            image_obj.position = next_position
            changed = True

        raw_alt = str(getattr(image_obj, "alt_text", "") or "").strip()
        if not raw_alt:
            caption = str(getattr(image_obj, "caption", "") or "").strip()
            if caption:
                fallback_alt = caption
            else:
                sheet = getattr(image_obj, "sheet", None)
                sheet_title = str(getattr(sheet, "titre", "") or "").strip()
                if not sheet_title and sheet is not None:
                    notion = getattr(sheet, "notion", None)
                    sheet_title = str(getattr(notion, "titre", "") or "").strip()
                humanized_name = _humanize_filename(getattr(getattr(image_obj, "image", None), "name", ""))
                if sheet_title and humanized_name:
                    fallback_alt = f"{sheet_title} - {humanized_name}"
                elif sheet_title:
                    fallback_alt = f"{sheet_title} - illustration"
                elif humanized_name:
                    fallback_alt = humanized_name
                else:
                    fallback_alt = "Illustration de synthese"
            image_obj.alt_text = fallback_alt
            changed = True

        raw_title = str(getattr(image_obj, "title_text", "") or "").strip()
        if not raw_title:
            fallback_title = _humanize_filename(getattr(getattr(image_obj, "image", None), "name", ""))
            if fallback_title:
                image_obj.title_text = fallback_title
                changed = True

        if changed:
            to_update.append(image_obj)

    if to_update:
        SynthesisImage.objects.bulk_update(
            to_update,
            ["position", "alt_text", "title_text"],
            batch_size=1000,
        )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("synthesis", "0009_alter_synthesissheet_sheet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="synthesisimage",
            name="alt_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="synthesisimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synthesisimage",
            name="title_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="synthesisimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(resequence_positions_and_fill_seo, reverse_noop),
        migrations.AddConstraint(
            model_name="synthesisimage",
            constraint=models.UniqueConstraint(
                condition=Q(position__isnull=False),
                fields=("sheet", "position"),
                name="unique_synthesisimage_position_per_sheet",
            ),
        ),
    ]
