# Generated by Django 5.2.4 on 2025-08-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('code_iso', models.CharField(max_length=3, unique=True)),
                ('drapeau_emoji', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('couleur', models.CharField(default='#3b82f6', max_length=7)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='pays.pays')),
            ],
            options={
                'verbose_name_plural': 'Niveaux par pays',
                'ordering': ['pays', 'ordre', 'nom'],
                'unique_together': {('pays', 'nom')},
            },
        ),
    ]
