# Generated by Django 5.2.4 on 2026-03-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_exerciceimage_seo_fields'),
        ('pays', '0002_niveau_exercice_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='demo_exercices',
            field=models.ManyToManyField(blank=True, help_text='Exercices débloqués gratuitement (du chapitre démo)', related_name='+', to='curriculum.exercice', verbose_name='Exercices démo'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='demo_notion',
            field=models.ForeignKey(blank=True, help_text='Notion (chapitre) débloquée gratuitement pour ce niveau', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.notion', verbose_name='Chapitre démo'),
        ),
    ]
