# Generated by Django 5.2.4 on 2026-03-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_robots',
            field=models.CharField(blank=True, choices=[('index', 'index, follow'), ('noindex', 'noindex, follow')], default='index', max_length=50, verbose_name='Meta robots'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='alt_text_image',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Alt text image couverture'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_robots',
            field=models.CharField(blank=True, choices=[('index', 'index, follow'), ('noindex', 'noindex, follow')], default='index', max_length=50, verbose_name='Meta robots'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/og/%Y/%m/', verbose_name='Image OG (Open Graph)'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='meta_robots',
            field=models.CharField(blank=True, choices=[('index', 'index, follow'), ('noindex', 'noindex, follow')], default='index', max_length=50, verbose_name='Meta robots'),
        ),
    ]
