# Generated by Django 5.2.4 on 2026-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='niveau',
            field=models.CharField(
                blank=True,
                choices=[
                    ('seconde', 'Seconde'),
                    ('premiere', 'Première'),
                    ('terminale', 'Terminale'),
                    ('prepa', 'Prépa'),
                ],
                default='',
                max_length=20,
                verbose_name='Niveau',
            ),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='type_contenu',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cours', 'Cours'),
                    ('methode', 'Méthode'),
                    ('exercice_corrige', 'Exercice corrigé'),
                    ('erreur_frequente', 'Erreur fréquente'),
                    ('revision_bac', 'Révision bac'),
                ],
                default='',
                max_length=30,
                verbose_name='Type de contenu',
            ),
        ),
    ]
