# Generated by Codex on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(model, raw_value, fallback_prefix, using):
    base = slugify(raw_value or '')[:90]
    if not base:
        base = fallback_prefix

    slug = base
    index = 2
    while model.objects.using(using).filter(slug=slug).exists():
        suffix = f'-{index}'
        slug = f'{base[:100 - len(suffix)]}{suffix}'
        index += 1
    return slug


def forwards_convert_taxonomies(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogNiveau = apps.get_model('blog', 'BlogNiveau')
    BlogContentType = apps.get_model('blog', 'BlogContentType')

    default_niveaux = [
        ('seconde', 'Seconde', 10),
        ('premiere', 'Première', 20),
        ('terminale', 'Terminale', 30),
        ('prepa', 'Prépa', 40),
    ]
    default_types = [
        ('cours', 'Cours', 10),
        ('methode', 'Méthode', 20),
        ('exercice_corrige', 'Exercice corrigé', 30),
        ('erreur_frequente', 'Erreur fréquente', 40),
        ('revision_bac', 'Révision bac', 50),
    ]

    niveaux_by_key = {}
    for slug, nom, ordre in default_niveaux:
        niveau, _ = BlogNiveau.objects.using(db_alias).get_or_create(
            slug=slug,
            defaults={
                'nom': nom,
                'ordre': ordre,
                'est_actif': True,
            },
        )
        niveaux_by_key[slug] = niveau
        niveaux_by_key[nom.lower()] = niveau

    types_by_key = {}
    for slug, nom, ordre in default_types:
        content_type, _ = BlogContentType.objects.using(db_alias).get_or_create(
            slug=slug,
            defaults={
                'nom': nom,
                'ordre': ordre,
                'est_actif': True,
            },
        )
        types_by_key[slug] = content_type
        types_by_key[nom.lower()] = content_type

    niveau_values = (
        BlogPost.objects.using(db_alias)
        .exclude(niveau__isnull=True)
        .exclude(niveau='')
        .values_list('niveau', flat=True)
        .distinct()
    )
    for raw in niveau_values:
        value = (raw or '').strip()
        if not value:
            continue
        key = value.lower()
        niveau = niveaux_by_key.get(key)
        if niveau is None:
            nom = value.replace('_', ' ').strip().capitalize()
            slug = _unique_slug(BlogNiveau, value, 'niveau', db_alias)
            niveau = BlogNiveau.objects.using(db_alias).create(
                nom=nom,
                slug=slug,
                ordre=999,
                est_actif=True,
            )
            niveaux_by_key[key] = niveau
        BlogPost.objects.using(db_alias).filter(niveau=raw).update(niveau_ref=niveau)

    type_values = (
        BlogPost.objects.using(db_alias)
        .exclude(type_contenu__isnull=True)
        .exclude(type_contenu='')
        .values_list('type_contenu', flat=True)
        .distinct()
    )
    for raw in type_values:
        value = (raw or '').strip()
        if not value:
            continue
        key = value.lower()
        content_type = types_by_key.get(key)
        if content_type is None:
            nom = value.replace('_', ' ').strip().capitalize()
            slug = _unique_slug(BlogContentType, value, 'type', db_alias)
            content_type = BlogContentType.objects.using(db_alias).create(
                nom=nom,
                slug=slug,
                ordre=999,
                est_actif=True,
            )
            types_by_key[key] = content_type
        BlogPost.objects.using(db_alias).filter(type_contenu=raw).update(type_contenu_ref=content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_niveau_type_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Type de contenu',
                'verbose_name_plural': 'Types de contenu',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='BlogNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='niveau_ref',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='articles',
                to='blog.blogniveau',
                verbose_name='Niveau',
            ),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='type_contenu_ref',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='articles',
                to='blog.blogcontenttype',
                verbose_name='Type de contenu',
            ),
        ),
        migrations.RunPython(forwards_convert_taxonomies, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='blogpost',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='type_contenu',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='niveau_ref',
            new_name='niveau',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='type_contenu_ref',
            new_name='type_contenu',
        ),
    ]
