# Generated by Django 5.2.4 on 2026-04-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpostrelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='blogpostrelatedlink',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='blogpostrelatedlink',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
