# Generated by Django 5.2.4 on 2025-08-12 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('pays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatiereContexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#3b82f6', max_length=7, verbose_name='Couleur')),
                ('svg_icon', models.TextField(blank=True, null=True, verbose_name='Icône SVG')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextes', to='curriculum.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_contexte', to='pays.niveau')),
            ],
            options={
                'verbose_name': 'Contexte Matière',
                'verbose_name_plural': 'Contextes Matière',
                'ordering': ['matiere', 'niveau__pays', 'niveau__ordre'],
                'unique_together': {('matiere', 'niveau')},
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='contexte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='curriculum.matierecontexte'),
        ),
    ]
