# Generated by Django 5.2.4 on 2025-08-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_matierecontexte_theme_contexte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='niveaux',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='notion',
            name='niveaux',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='niveaux',
        ),
    ]
