# Generated by Django 5.2.4 on 2025-08-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quiz_images/')),
                ('image_type', models.CharField(choices=[('question', 'Question'), ('answer', 'Réponse'), ('illustration', 'Illustration')], default='question', max_length=20)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('legende', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Image de quiz',
                'verbose_name_plural': 'Images de quiz',
                'ordering': ['quiz', 'position', 'id'],
                'indexes': [models.Index(fields=['quiz', 'position'], name='quiz_quizim_quiz_id_5d326a_idx')],
            },
        ),
    ]
