# Generated by Django 5.2.4 on 2025-09-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_chapitre_unique_together_and_more'),
        ('quiz', '0002_quizimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['notion', 'ordre'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='chapitre',
        ),
        migrations.AddField(
            model_name='quiz',
            name='notion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='curriculum.notion'),
        ),
    ]
