# Generated by Django 5.2.4 on 2025-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_options_remove_quiz_chapitre_quiz_notion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='solution',
            field=models.TextField(blank=True, default='', help_text="Solution complète du quiz, visible par l'élève après correction", verbose_name='Solution du quiz'),
        ),
    ]
