# Generated by Django 5.2.4 on 2026-05-05 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0017_exerciceimage_seo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, help_text='Tant que la valeur est False, seuls les administrateurs peuvent accéder au jeu.', verbose_name='Visible publiquement')),
                ('daily_xp_bonus', models.PositiveIntegerField(default=50)),
                ('streak_shield_enabled', models.BooleanField(default=True)),
                ('free_levels_per_chapter', models.PositiveIntegerField(default=2)),
                ('free_hints_per_day', models.PositiveIntegerField(default=1)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Arena',
                'verbose_name_plural': 'Configuration Arena',
            },
        ),
        migrations.CreateModel(
            name='ArenaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji ou code icône.', max_length=10)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False, help_text='Réserve tout le chapitre aux abonnés.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notion', models.ForeignKey(blank=True, help_text='Notion pédagogique liée (optionnel mais recommandé pour la cohérence).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_chapters', to='curriculum.notion')),
            ],
            options={
                'verbose_name': 'Chapitre Arena',
                'verbose_name_plural': 'Chapitres Arena',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ArenaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement Arena',
                'verbose_name_plural': 'Événements Arena',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile'), ('elite', 'Élite (premium)')], default='easy', max_length=10)),
                ('time_limit_sec', models.PositiveIntegerField(default=120)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('pass_threshold', models.PositiveIntegerField(default=60, help_text='Pourcentage minimal pour réussir.')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='mathgame.arenachapter')),
            ],
            options={
                'verbose_name': 'Niveau Arena',
                'verbose_name_plural': 'Niveaux Arena',
                'ordering': ['chapter', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ArenaDailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bonus_xp', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_uses', to='mathgame.arenalevel')),
            ],
            options={
                'verbose_name': 'Défi quotidien',
                'verbose_name_plural': 'Défis quotidiens',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArenaAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('used_hint', models.BooleanField(default=False)),
                ('is_daily', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_attempts', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mathgame.arenalevel')),
            ],
            options={
                'verbose_name': 'Tentative Arena',
                'verbose_name_plural': 'Tentatives Arena',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArenaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('mcq', 'Choix multiple'), ('numeric', 'Réponse numérique')], default='mcq', max_length=10)),
                ('prompt', models.TextField(help_text='Énoncé. LaTeX accepté entre $...$.')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Liste de propositions pour MCQ. Vide pour numeric.')),
                ('correct', models.JSONField(default=list, help_text="Pour MCQ: indices corrects, ex [0]. Pour numeric: ex {'value': 1.5, 'tolerance': 0.01}.")),
                ('hint', models.TextField(blank=True, default='', help_text='Indice (premium uniquement).')),
                ('explanation', models.TextField(blank=True, default='', help_text='Solution détaillée. Tronquée pour les utilisateurs non premium.')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mathgame.arenalevel')),
            ],
            options={
                'verbose_name': 'Question Arena',
                'verbose_name_plural': 'Questions Arena',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ArenaMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_wrong', models.PositiveIntegerField(default=1)),
                ('mastery', models.PositiveSmallIntegerField(default=0, help_text='0..3, 3 = maîtrisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_mistakes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='mathgame.arenaquestion')),
            ],
            options={
                'verbose_name': 'Erreur (Forge)',
                'verbose_name_plural': 'Erreurs (Forge)',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ArenaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mathgame.arenaattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mathgame.arenaquestion')),
            ],
            options={
                'verbose_name': 'Réponse Arena',
                'verbose_name_plural': 'Réponses Arena',
            },
        ),
        migrations.CreateModel(
            name='ArenaUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_played_date', models.DateField(blank=True, null=True)),
                ('streak_shields_used', models.PositiveIntegerField(default=0)),
                ('daily_hints_used', models.PositiveIntegerField(default=0)),
                ('daily_hints_reset_date', models.DateField(blank=True, null=True)),
                ('total_levels_completed', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('last_daily_completed_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'État joueur Arena',
                'verbose_name_plural': 'États joueurs Arena',
            },
        ),
        migrations.AddIndex(
            model_name='arenaattempt',
            index=models.Index(fields=['user', '-created_at'], name='mathgame_ar_user_id_b0c00b_idx'),
        ),
        migrations.AddIndex(
            model_name='arenaattempt',
            index=models.Index(fields=['level', '-score'], name='mathgame_ar_level_i_d0f4a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='arenaquestion',
            unique_together={('level', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='arenamistake',
            unique_together={('user', 'question')},
        ),
    ]
