# Generated by Django 5.2.4 on 2025-09-30 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('curriculum', '0006_alter_theme_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aiconversation',
            name='ai_aiconver_context_087723_idx',
        ),
        migrations.RemoveField(
            model_name='aiconversation',
            name='contexte_chapitre',
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='contexte_notion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='curriculum.notion'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['contexte_notion'], name='ai_aiconver_context_ba6b44_idx'),
        ),
    ]
