# Generated by Django 5.2.4 on 2025-08-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#3b82f6', max_length=7, verbose_name='Couleur')),
                ('svg_icon', models.TextField(blank=True, null=True, verbose_name='Icône SVG')),
                ('niveaux', models.ManyToManyField(blank=True, related_name='matieres', to='pays.niveau')),
                ('pays', models.ManyToManyField(blank=True, related_name='matieres', to='pays.pays')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#3b82f6', max_length=7, verbose_name='Couleur')),
                ('svg_icon', models.TextField(blank=True, null=True, verbose_name='Icône SVG')),
                ('niveaux', models.ManyToManyField(blank=True, related_name='notions', to='pays.niveau')),
            ],
            options={
                'verbose_name': 'Notion',
                'verbose_name_plural': 'Notions',
                'ordering': ['theme', 'ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10, verbose_name='Difficulté')),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='curriculum.notion')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['notion', 'ordre', 'titre'],
                'unique_together': {('notion', 'titre')},
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#3b82f6', max_length=7, verbose_name='Couleur')),
                ('svg_icon', models.TextField(blank=True, null=True, verbose_name='Icône SVG')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='curriculum.matiere')),
                ('niveaux', models.ManyToManyField(blank=True, related_name='themes', to='pays.niveau')),
            ],
            options={
                'verbose_name': 'Thème',
                'verbose_name_plural': 'Thèmes',
                'ordering': ['matiere', 'ordre', 'titre'],
                'unique_together': {('matiere', 'titre')},
            },
        ),
        migrations.AddField(
            model_name='notion',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notions', to='curriculum.theme'),
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10, verbose_name='Difficulté')),
                ('question', models.TextField()),
                ('reponse_correcte', models.TextField()),
                ('points', models.PositiveIntegerField(default=1)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='curriculum.chapitre')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['chapitre', 'ordre', 'titre'],
                'unique_together': {('chapitre', 'titre')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='notion',
            unique_together={('theme', 'titre')},
        ),
    ]
