# Generated by Django 5.2.4 on 2025-08-13 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_matiere_niveaux_remove_matiere_pays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exercice_images/')),
                ('image_type', models.CharField(choices=[('donnee', 'Donnée'), ('solution', 'Solution'), ('illustration', 'Illustration')], default='donnee', max_length=20)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('legende', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='curriculum.exercice')),
            ],
            options={
                'verbose_name': "Image d'exercice",
                'verbose_name_plural': "Images d'exercice",
                'ordering': ['exercice', 'position', 'id'],
                'indexes': [models.Index(fields=['exercice', 'position'], name='curriculum__exercic_178924_idx')],
            },
        ),
    ]
