# Generated by Django 5.2.4 on 2025-08-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_exerciceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='etapes',
            field=models.TextField(blank=True, null=True, verbose_name='Étapes de résolution'),
        ),
    ]
