# Generated by Django 5.2.4 on 2025-09-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_exercice_etapes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('contexte', 'titre')},
        ),
    ]
