# Generated by Django 5.2.4 on 2025-09-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_theme_unique_together'),
    ]

    operations = [
        # Rendre l'ajout de la colonne notion_id idempotent côté base, tout en maintenant l'état Django
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE curriculum_exercice "
                        "ADD COLUMN IF NOT EXISTS notion_id integer;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Index optionnel et contrainte FK si non existants (sûr à ré-exécuter)
                migrations.RunSQL(
                    sql=(
                        "CREATE INDEX IF NOT EXISTS curriculum_exercice_notion_id_idx "
                        "ON curriculum_exercice (notion_id);"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        "DO $$\n"
                        "BEGIN\n"
                        "IF NOT EXISTS (\n"
                        "    SELECT 1 FROM pg_constraint c\n"
                        "    JOIN pg_class t ON c.conrelid = t.oid\n"
                        "    WHERE t.relname = 'curriculum_exercice'\n"
                        "      AND c.conname = 'curriculum_exercice_notion_id_fkey'\n"
                        ") THEN\n"
                        "    ALTER TABLE curriculum_exercice\n"
                        "    ADD CONSTRAINT curriculum_exercice_notion_id_fkey\n"
                        "    FOREIGN KEY (notion_id) REFERENCES curriculum_notion(id)\n"
                        "    ON DELETE CASCADE;\n"
                        "END IF;\n"
                        "END$$;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='exercice',
                    name='notion',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='curriculum.notion'),
                ),
            ],
        ),
        # Supprimer l'ancienne colonne chapitre_id si elle existe, et retirer le champ côté état Django
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE curriculum_exercice DROP COLUMN IF EXISTS chapitre_id CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='exercice',
                    name='chapitre',
                ),
            ],
        ),
    ]
