# Generated by Django 5.2.4 on 2025-09-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_aiconversation_ai_aiconver_context_087723_idx_and_more'),
        ('cours', '0003_alter_cours_options_remove_cours_chapitre_and_more'),
        ('curriculum', '0007_alter_chapitre_unique_together_and_more'),
        ('quiz', '0003_alter_quiz_options_remove_quiz_chapitre_quiz_notion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapitre',
        ),
    ]
