# Generated by Django 5.2.4 on 2025-09-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_delete_chapitre'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=migrations.RunSQL.noop, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.AlterModelOptions(
                    name='exercice',
                    options={
                        'ordering': ['notion', 'ordre', 'titre'],
                        'verbose_name': 'Exercice',
                        'verbose_name_plural': 'Exercices',
                    },
                ),
                migrations.AlterUniqueTogether(
                    name='exercice',
                    unique_together={('notion', 'titre')},
                ),
            ],
        ),
    ]
