# Generated by Django 5.2.4 on 2025-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_matiere_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='access_scope',
            field=models.CharField(choices=[('paid', 'Abonnés uniquement'), ('free', 'Gratuit (découverte)'), ('both', 'Gratuit + Abonnés')], default='paid', help_text='Définit si ce contenu est gratuit, payant ou visible dans les deux parcours.', max_length=10),
        ),
    ]
