# Generated by Django 5.2.4 on 2025-11-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_exercice_access_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='access_scope',
        ),
    ]
