[[redirects]]
  from = "https://www.optitab.net/*"
  to = "https://optitab.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.optitab.net/*"
  to = "https://optitab.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://optitab.net/*"
  to = "https://optitab.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/cours-en-ligne"
  to = "/cours-particuliers"
  status = 301

[[redirects]]
  from = "/soutien-scolaire"
  to = "/cours-particuliers"
  status = 301

[[redirects]]
  from = "/aide-aux-devoirs"
  to = "/cours-particuliers"
  status = 301

[[redirects]]
  from = "/ressources-gratuites"
  to = "/ressources-gratuites/cours"
  status = 301

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"
