# Generated by Django 5.2.4 on 2025-08-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('temps_total_seconde', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reponse_donnee', models.TextField()),
                ('est_correct', models.BooleanField(default=False)),
                ('points_obtenus', models.PositiveIntegerField(default=0)),
                ('temps_seconde', models.PositiveIntegerField(default=0)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.exercice')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
