# Generated by Django 5.2.4 on 2025-12-11 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_options_remove_quiz_chapitre_quiz_notion'),
        ('suivis', '0003_suiviquiz_gamification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('graded', 'Noté')], default='pending', max_length=20)),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Note sur 20', max_digits=5, null=True)),
                ('commentaire', models.TextField(blank=True, default='', help_text='Commentaire de correction')),
                ('date_correction', models.DateTimeField(blank=True, help_text='Date de correction', null=True)),
                ('notes_admin', models.TextField(blank=True, default='', help_text="Notes privées pour l'admin")),
                ('corrige_par', models.ForeignKey(blank=True, help_text='Administrateur qui a corrigé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_corriges', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soumission de quiz',
                'verbose_name_plural': 'Soumissions de quiz',
                'ordering': ['-date_creation'],
            },
        ),
    ]
