# Generated by Django 5.2.4 on 2025-08-13 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('parent', 'Parent')], db_index=True, default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien parent-enfant',
                'verbose_name_plural': 'Liens parents-enfants',
                'indexes': [models.Index(fields=['parent', 'child'], name='users_paren_parent__e314ac_idx')],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
