# Generated by Django 5.2.4 on 2025-08-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role_parentchild'),
        ('users', '0003_reset_xp_levels'),
    ]

    operations = [
    ]
