# Generated by Django 5.2.4 on 2025-08-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250816_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('xp_gained', 'XP Gained'), ('level_up', 'Level Up'), ('exercise_unlocked', 'Exercise Unlocked'), ('chapter_completed', 'Chapter Completed'), ('achievement', 'Achievement'), ('daily_streak', 'Daily Streak')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='users_usern_user_id_55f2d2_idx')],
            },
        ),
    ]
