# Generated by Django 5.2.4 on 2025-09-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_optimize_auth_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_email_1a70ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_is_acti_2fbc71_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_role_e4c2f2_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
