# Generated by Django 5.2.4 on 2025-10-09 18:22

from django.db import migrations, models


def sync_share_history_field(apps, schema_editor):
    """
    Sync the share_history_with_parents field.
    The column already exists in the database, so we just need to ensure
    any NULL values are set to False.
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Update any NULL values to False
        cursor.execute("""
            UPDATE users_customuser 
            SET share_history_with_parents = FALSE 
            WHERE share_history_with_parents IS NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_streak'),
    ]

    operations = [
        # First, sync any existing data
        migrations.RunPython(sync_share_history_field, migrations.RunPython.noop),
        # Then add the field (will be a no-op if column already exists in DB)
        migrations.AddField(
            model_name='customuser',
            name='share_history_with_parents',
            field=models.BooleanField(default=False, help_text="Autoriser les parents à voir l'historique d'apprentissage", verbose_name="Partager l'historique avec les parents"),
        ),
    ]
