# Generated by Django 5.2.4 on 2025-10-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_streak'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        ALTER TABLE users_customuser
                        ADD COLUMN IF NOT EXISTS share_history_with_parents boolean;

                        UPDATE users_customuser
                        SET share_history_with_parents = FALSE
                        WHERE share_history_with_parents IS NULL;

                        ALTER TABLE users_customuser
                        ALTER COLUMN share_history_with_parents SET DEFAULT FALSE;

                        ALTER TABLE users_customuser
                        ALTER COLUMN share_history_with_parents SET NOT NULL;
                        """
                    ),
                    reverse_sql=(
                        """
                        ALTER TABLE users_customuser
                        DROP COLUMN IF EXISTS share_history_with_parents;
                        """
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='customuser',
                    name='share_history_with_parents',
                    field=models.BooleanField(
                        default=False,
                        help_text="Autoriser les parents à voir l'historique d'apprentissage",
                        verbose_name="Partager l'historique avec les parents",
                    ),
                ),
            ],
        ),
    ]
