# Generated by Django 5.2.4 on 2025-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_share_history_with_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_streak_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de jours consécutifs connectés', verbose_name='Série de connexions (jours consécutifs)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_streak_last_date',
            field=models.DateField(blank=True, help_text='Dernière date (locale) où la récompense quotidienne a été attribuée', null=True, verbose_name='Dernière date de récompense quotidienne'),
        ),
    ]
