# Generated by Django 5.2.4 on 2025-11-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cleanup_legacy_streak_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_complimentary_access',
            field=models.BooleanField(default=False, help_text="Autorise l'accès aux contenus premium sans abonnement actif ou pass.", verbose_name='Accès premium offert'),
        ),
    ]
