# Generated by Django 5.2.4 on 2025-11-02 11:58

from django.db import migrations, models
from django.utils import timezone


def set_existing_links_as_accepted(apps, schema_editor):
    ParentChild = apps.get_model('users', 'ParentChild')
    now = timezone.now()
    ParentChild.objects.filter(status='pending').update(
        status='accepted',
        responded_at=now,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_has_complimentary_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchild',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentchild',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('xp_gained', 'XP Gained'), ('level_up', 'Level Up'), ('exercise_unlocked', 'Exercise Unlocked'), ('chapter_completed', 'Chapter Completed'), ('achievement', 'Achievement'), ('parent_invite', 'Parent Invite'), ('parent_invite_response', 'Parent Invite Response')], max_length=50),
        ),
        migrations.RunPython(set_existing_links_as_accepted, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='parentchild',
            index=models.Index(fields=['parent', 'status'], name='users_paren_parent__d4a8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchild',
            index=models.Index(fields=['child', 'status'], name='users_paren_child_i_dacd2d_idx'),
        ),
    ]
