# Generated by Django 5.2.4 on 2026-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_complimentary_access_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='complimentary_access_ends_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de fin de validité. Laisser vide pour un accès sans date de fin.', null=True, verbose_name='Fin accès premium offert'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='complimentary_access_starts_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de début de validité. Laisser vide pour un accès immédiat.', null=True, verbose_name='Début accès premium offert'),
        ),
    ]
