# Generated by Django 5.2.4 on 2025-09-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0005_exercice_etapes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('message', models.TextField(verbose_name="Message de l'utilisateur")),
                ('ai_response', models.TextField(verbose_name="Réponse de l'IA")),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens utilisés')),
                ('model_used', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='Modèle IA utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contexte_chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='curriculum.chapitre')),
                ('contexte_matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='curriculum.matierecontexte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_aiconver_user_id_317f36_idx'), models.Index(fields=['contexte_matiere'], name='ai_aiconver_context_f0ca99_idx'), models.Index(fields=['contexte_chapitre'], name='ai_aiconver_context_087723_idx')],
            },
        ),
    ]
