# Generated by Django 5.2.4 on 2025-10-27 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Nom')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='Source')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Jeton de désinscription')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Désabonné le')),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier email envoyé')),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de consentement')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-date_creation'],
            },
        ),
    ]
