# Generated by Django 5.2.4 on 2026-05-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diagnosticlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticlead',
            name='difficulty_other',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Difficulté précisée (texte libre)'),
        ),
        migrations.AlterField(
            model_name='diagnosticlead',
            name='difficulty',
            field=models.CharField(choices=[('cours_vs_exercices', 'Comprend le cours mais pas les exercices'), ('organisation', 'Organisation / révision'), ('methode', 'Pas de méthode claire'), ('bac', 'Préparation Bac'), ('motivation', 'Motivation'), ('autre', 'Autre (texte libre)')], db_index=True, max_length=30, verbose_name='Difficulté principale'),
        ),
    ]
