# Generated by Django 5.2.4 on 2026-07-29 08:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_difficulty_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('author', models.CharField(help_text='Prenom + initiale uniquement, ex. « Sandra M. ». Jamais le nom complet.', max_length=80, verbose_name='Auteur')),
                ('role', models.CharField(blank=True, help_text='Ex. « Maman de Lea · Terminale » ou « Terminale ».', max_length=120, verbose_name='Contexte')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20, verbose_name='Canal')),
                ('image', models.ImageField(help_text="Numero, photo de profil et nom complet doivent etre masques avant l'envoi.", upload_to=core.models.testimonial_image_upload_to, verbose_name='Capture')),
                ('alt_text', models.CharField(blank=True, help_text="Decrit la capture pour l'accessibilite et le referencement.", max_length=255, verbose_name='Texte alternatif')),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Obligatoire pour publier : confirme que la personne autorise la diffusion.', verbose_name='Accord obtenu')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publie')),
                ('is_featured', models.BooleanField(default=False, help_text='Affiche aussi dans le hero. Un seul temoignage a la fois.', verbose_name='Mis en avant')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Temoignage',
                'verbose_name_plural': 'Temoignages',
                'ordering': ['ordre', '-date_creation'],
                'indexes': [models.Index(fields=['is_published', 'ordre'], name='core_testim_is_publ_4d8758_idx')],
            },
        ),
    ]
