# Generated by Django 5.2.4 on 2026-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(blank=True, choices=[("Maman d'élève", "Maman d'élève"), ("Papa d'élève", "Papa d'élève"), ("Parent d'élève", "Parent d'élève"), ('Élève', 'Élève'), ('Étudiant', 'Étudiant'), ('Étudiante', 'Étudiante')], help_text='Qui a ecrit le message. Jamais de nom ni de prenom.', max_length=80, verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text="Ex. « Terminale », « Prepa MPSI ». Sans prenom d'enfant.", max_length=120, verbose_name='Niveau'),
        ),
    ]
