# Generated by Django 5.2.4 on 2026-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_testimonial_author_alter_testimonial_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='display_name',
            field=models.CharField(blank=True, help_text='Prenom + initiale, ex. « Sandra M. ». Jamais le nom complet.', max_length=60, verbose_name='Prenom affiche'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_consent',
            field=models.BooleanField(default=False, help_text="La personne autorise explicitement l'affichage de son prenom.", verbose_name='Accord pour le prenom'),
        ),
    ]
