# Generated by Django 5.2.4 on 2026-07-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonial_display_name_testimonial_name_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='consent_confirmed',
            field=models.BooleanField(default=False, help_text='Trace interne. Ne bloque pas la publication.', verbose_name='Accord obtenu'),
        ),
    ]
