# Generated by Django 5.2.4 on 2026-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testimonial_consent_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioLandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_published', models.BooleanField(default=False, help_text='Decoche : seuls les administrateurs voient la page.', verbose_name='Page en ligne')),
            ],
            options={
                'verbose_name': 'Reglages page avis',
                'verbose_name_plural': 'Reglages page avis',
            },
        ),
    ]
